export const ANM = [
    {
        title: "Naruto",
        type: "anime",
        genre: "Action, Adventure",
        episodes: 220,
        rating: 8.3,
        releaseYear: 2002,
        studios: "Pierrot",
        synopsis: "Naruto Uzumaki, um jovem ninja com um demônio selado dentro dele, busca reconhecimento e sonha em se tornar o Hokage, o líder de sua vila.",
        status: "Completed"
    },
    {
        title: "Attack on Titan",
        type: "anime",
        genre: "Action, Fantasy",
        episodes: 75,
        rating: 8.9,
        releaseYear: 2013,
        studios: "Wit Studio, MAPPA",
        synopsis: "A humanidade luta para sobreviver contra gigantes devoradores de homens conhecidos como Titãs.",
        status: "Ongoing"
    },
    {
        title: "One Piece",
        type: "manga",
        genre: "Action, Adventure",
        episodes: null,
        rating: 8.7,
        releaseYear: 1997,
        studios: null,
        synopsis: "Monkey D. Luffy e sua tripulação de piratas exploram o oceano em busca do lendário tesouro One Piece.",
        status: "Ongoing"
    },
    {
        title: "Death Note",
        type: "manga",
        genre: "Mystery, Psychological",
        episodes: null,
        rating: 8.8,
        releaseYear: 2003,
        studios: null,
        synopsis: "Um estudante do ensino médio encontra um caderno que lhe dá o poder de matar qualquer pessoa cujo nome ele escreva nele.",
        status: "Completed"
    },
    {
        title: "Sword Art Online",
        type: "novel",
        genre: "Action, Adventure",
        episodes: null,
        rating: 7.5,
        releaseYear: 2009,
        studios: null,
        synopsis: "Jogadores ficam presos em um MMORPG virtual onde a morte no jogo significa a morte na vida real.",
        status: "Ongoing"
    },
    {
        title: "My Hero Academia",
        type: "anime",
        genre: "Action, Comedy",
        episodes: 88,
        rating: 8.0,
        releaseYear: 2016,
        studios: "Bones",
        synopsis: "Em um mundo onde quase todos possuem superpoderes, um jovem sem poderes sonha em se tornar o maior herói.",
        status: "Ongoing"
    },
    {
        title: "Tokyo Ghoul",
        type: "manga",
        genre: "Action, Drama",
        episodes: null,
        rating: 8.0,
        releaseYear: 2011,
        studios: null,
        synopsis: "Um jovem estudante se torna meio-ghoul após um encontro mortal e deve se ajustar à sua nova vida.",
        status: "Completed"
    },
    {
        title: "Re:Zero - Starting Life in Another World",
        type: "novel",
        genre: "Fantasy, Drama",
        episodes: null,
        rating: 8.3,
        releaseYear: 2012,
        studios: null,
        synopsis: "Subaru Natsuki é transportado para um mundo de fantasia onde ele tem o poder de reviver após a morte.",
        status: "Ongoing"
    },
    {
        title: "Demon Slayer: Kimetsu no Yaiba",
        type: "anime",
        genre: "Action, Supernatural",
        episodes: 26,
        rating: 8.7,
        releaseYear: 2019,
        studios: "Ufotable",
        synopsis: "Tanjiro Kamado se torna um caçador de demônios para vingar sua família e curar sua irmã.",
        status: "Completed"
    },
    {
        title: "No Game No Life",
        type: "anime",
        genre: "Adventure, Comedy",
        episodes: 12,
        rating: 7.8,
        releaseYear: 2014,
        studios: "Madhouse",
        synopsis: "Dois irmãos prodígios dos jogos são transportados para um mundo onde tudo é decidido por jogos.",
        status: "Completed"
    },
    {
        title: "Your Name",
        type: "anime",
        genre: "Drama, Romance",
        episodes: 1,
        rating: 8.9,
        releaseYear: 2016,
        studios: "CoMix Wave Films",
        synopsis: "Dois adolescentes misteriosamente trocam de corpos e devem lidar com os desafios de viver a vida do outro.",
        status: "Completed"
    },
    {
        title: "Bleach",
        type: "manga",
        genre: "Action, Supernatural",
        episodes: null,
        rating: 8.0,
        releaseYear: 2001,
        studios: null,
        synopsis: "Ichigo Kurosaki, que pode ver espíritos, se torna um Ceifador de Almas para proteger os vivos e os mortos.",
        status: "Completed"
    },
    {
        title: "Overlord",
        type: "novel",
        genre: "Action, Fantasy",
        episodes: null,
        rating: 8.1,
        releaseYear: 2010,
        studios: null,
        synopsis: "Um jogador fica preso em seu jogo de realidade virtual favorito quando os servidores são encerrados.",
        status: "Ongoing"
    },
    {
        title: "Steins;Gate",
        type: "anime",
        genre: "Sci-Fi, Thriller",
        episodes: 24,
        rating: 9.1,
        releaseYear: 2011,
        studios: "White Fox",
        synopsis: "Um cientista louco e seus amigos descobrem um meio de enviar mensagens para o passado.",
        status: "Completed"
    },
    {
        title: "Fate/Stay Night: Unlimited Blade Works",
        type: "anime",
        genre: "Action, Fantasy",
        episodes: 26,
        rating: 8.2,
        releaseYear: 2014,
        studios: "Ufotable",
        synopsis: "Shirou Emiya se vê envolvido em uma guerra secreta entre magos para obter o Santo Graal.",
        status: "Completed"
    },
    {
        title: "The Rising of the Shield Hero",
        type: "novel",
        genre: "Action, Fantasy",
        episodes: null,
        rating: 8.0,
        releaseYear: 2013,
        studios: null,
        synopsis: "Naofumi Iwatani é transportado para um mundo de fantasia e se torna o Herói do Escudo.",
        status: "Ongoing"
    },
    {
        title: "The Promised Neverland",
        type: "manga",
        genre: "Mystery, Thriller",
        episodes: null,
        rating: 8.4,
        releaseYear: 2016,
        studios: null,
        synopsis: "Crianças em um orfanato descobrem a terrível verdade sobre seu destino e planejam uma fuga ousada.",
        status: "Completed"
    },
    {
        title: "That Time I Got Reincarnated as a Slime",
        type: "novel",
        genre: "Adventure, Fantasy",
        episodes: null,
        rating: 8.1,
        releaseYear: 2013,
        studios: null,
        synopsis: "Um homem comum é reencarnado em um mundo de fantasia como um slime com habilidades únicas.",
        status: "Ongoing"
    },
    {
        title: "Fullmetal Alchemist: Brotherhood",
        type: "anime",
        genre: "Action, Adventure",
        episodes: 64,
        rating: 9.2,
        releaseYear: 2009,
        studios: "Bones",
        synopsis: "Dois irmãos alquimistas buscam a Pedra Filosofal para restaurar seus corpos após um experimento fracassado.",
        status: "Completed"
    },
    {
        title: "Hunter x Hunter",
        type: "manga",
        genre: "Action, Adventure",
        episodes: null,
        rating: 8.9,
        releaseYear: 1998,
        studios: null,
        synopsis: "Gon Freecss decide se tornar um Hunter e encontrar seu pai, um lendário Hunter.",
        status: "Ongoing"
    },
    {
        title: "Goblin Slayer",
        type: "novel",
        genre: "Action, Fantasy",
        episodes: null,
        rating: 7.7,
        releaseYear: 2016,
        studios: null,
        synopsis: "Um guerreiro conhecido como Goblin Slayer dedica sua vida a exterminar goblins.",
        status: "Ongoing"
    },
    {
        title: "Vinland Saga",
        type: "manga",
        genre: "Action, Historical",
        episodes: null,
        rating: 8.6,
        releaseYear: 2005,
        studios: null,
        synopsis: "A história de Thorfinn, um jovem guerreiro viking que busca vingança contra Askeladd, o homem que matou seu pai.",
        status: "Ongoing"
    },
    {
        title: "Spice and Wolf",
        type: "novel",
        genre: "Adventure, Fantasy",
        episodes: null,
        rating: 8.3,
        releaseYear: 2006,
        studios: null,
        synopsis: "Um mercador itinerante faz parceria com uma deusa loba em uma jornada para retornar ao norte.",
        status: "Ongoing"
    },
    {
        title: "Black Clover",
        type: "anime",
        genre: "Action, Fantasy",
        episodes: 170,
        rating: 7.9,
        releaseYear: 2017,
        studios: "Pierrot",
        synopsis: "Asta e Yuno, dois órfãos criados juntos, competem para se tornar o Rei Mago.",
        status: "Ongoing"
    },
    {
        title: "Konosuba: God's Blessing on This Wonderful World!",
        type: "novel",
        genre: "Comedy, Fantasy",
        episodes: null,
        rating: 8.1,
        releaseYear: 2013,
        studios: null,
        synopsis: "Após uma morte embaraçosa, um jovem é ressuscitado em um mundo de fantasia com a missão de derrotar o Rei Demônio.",
        status: "Ongoing"
    },
    {
        title: "JoJo's Bizarre Adventure",
        type: "anime",
        genre: "Action, Supernatural",
        episodes: 152,
        rating: 8.5,
        releaseYear: 2012,
        studios: "David Production",
        synopsis: "As aventuras bizarras da família Joestar, que possui poderes psíquicos únicos.",
        status: "Ongoing"
    },
    {
        title: "The Seven Deadly Sins",
        type: "manga",
        genre: "Action, Fantasy",
        episodes: null,
        rating: 7.8,
        releaseYear: 2012,
        studios: null,
        synopsis: "Os Cavaleiros Sagrados de Britannia tentam restaurar a ordem ao reino ao lado da princesa Elizabeth.",
        status: "Completed"
    }
];